#!/bin/bash

STARTDIR=`pwd`
SRC=$STARTDIR/src
ENYO="$SRC/enyo"

# build deployable version
if command -v node >/dev/null 2>&1; then
	cd $SRC
	node "$ENYO/tools/deploy.js"
	cp icon* deploy/src
	cp manifest.webapp deploy/src
	cd deploy/src
	mkdir -p "$STARTDIR/bin/release"
	mkdir -p "$STARTDIR/bin/debug"
	rm -r -f "$STARTDIR/bin/debug/*"
	cp -r * "$STARTDIR/bin/debug"
	zip - -r * > "$STARTDIR/bin/release/package.zip"
	rm manifest.webapp
	cd "$SRC"
else
	echo "No node found in path; unable to build release version"
	exit 1
fi

if [ -f "$STARTDIR/deploy" ]
then
    cd $STARTDIR
    . $STARTDIR/deploy
fi
